sudo: true
language: node_js
node_js:
- 6
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
install:
- yarn install
script:
- echo $TRAVIS_BRANCH
before_deploy:
- REACT_APP_VERSION="$TRAVIS_BRANCH-$TRAVIS_COMMIT" REACT_APP_API_BASE="https://api.artee.party"
  yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token: "$FIREBASE_TOKEN"
  project: artee-177801
  on:
    branch: master
env:
  global:
    secure: Kf8oTggoacv0Gp/VXGul0CvmjIJLpjYRVTXvPDnqmf0BgJgQA7h+g1FkVfcNXQCHXwQ7iPuq451PwkAVEOOfx+yleOXR1XdCgrYPnKVNJWUCToG/2WuQh0wGUGPoaPo46b/SftRYssENHYz8HFy1naQX+NLuEIw3V9XpZc+xA5fAPpDfHT8Brxn/8RijpAGnkGmaJkP8N+flW9+CIFcPMy02KvuGmiHc5iN4jXCh2U+eDloNu1NCoFQgABQx7/Hwuxc5bto4hMkgqywHdt0pDB+0A8NnjYI7zkekq8wiCjr+rOWJbQHetS9PUB97JSiy/GX5ojyXRKVVzL7VPoQVf55k11Csdiegtsq6J8YQ44rAPFevi1rmPUcxBY10HBvy/gLIsqzxFgDm856b37QMw+TDyNiYP8SuIEqj82Cx5AKhCL13fE0zbqtHicjDrpJmp6zpuEDy7ZNUKJyYvm7dqDgLF4/kW7JDrBI3KRf3XrrDpjyS9JPuVxsXLlKD8uxS8rOJU1kgY3qQmBC+lsRpl9om99lkSNwUIx4MDDRFITXbOZVIln3pDchg5pNXPffkot0Gxd6sWK41bHl32S2KrXRiJlEyB1QudPTo506viwRHRS+/QvgITp3T5l1PatpOaQR3nwaoO1ri0sWGRHwCQRqe8Q9R9RID/+CMQlgiob4=
